export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children,analytics,team}) {
  return (
    <div>
      <h3>Dashboard Nav</h3>
      {children}
      {analytics}
      {team}
    </div>
  );
}